repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 15.12.0
    namespace: prometheus
    createNamespace: true
    kubeContext: minikube
    values:
      - ./values.yaml
