repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    chart: grafana/grafana
    version: 6.37.3
    namespace: grafana
    createNamespace: true
    kubeContext: minikube
    values:
      - ./values.yaml
