repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 39.12.0
    namespace: kube-prometheus-stack
    createNamespace: true
    kubeContext: minikube
    values:
      - ./values.yaml
