repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-adapter
    chart: prometheus-community/prometheus-adapter
    version: 3.4.0
    namespace: prometheus-adapter
    createNamespace: true
    kubeContext: minikube
    values:
      - ./values.yaml
